name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - run: bundle lock
      
      - name: Building the website 
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: 🚀 Deploying the website 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHACTION_TOKEN }}
          publish_dir: ./_site
          cname: justinkottinger.com
